# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
r:
  - oldrel
  - release
  - devel
sudo: false
warnings_are_errors: true
cache: packages
r_packages: 
  - testthat
  - roxygen2

after_success:
  - Rscript -e 'devtools::install();devtools::test()'
